server:
  port: 30100

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:oracle:thin:@192.168.1.9:1521:prod
    username: nimg
    password: nimg
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长
      idle-timeout: 600000 # 连接闲置状态的最大时长
      maximum-pool-size: 60 # 连接池中允许的最大连接数, 推荐的公式：((core_count * 2) + effective_spindle_count)
      max-lifetime: 1800000 # 连接的生命时长, 建议设置比数据库超时时长少30秒
      minimum-idle: 10
      read-only: false # 连接只读数据库时配置为true, 保证安全

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.1.9:20000/eureka

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true